### ISSUE TITLE
HarmonyX cannot patch other Assemblies loaded in another AppDomains

### ISSUE THREAD

**Issue by albgen** [BepInEx/HarmonyX#10]
hi,

I don't know if it is a feature request or a bug but here it is my scenario which is not working.

Describe the bug
I have 2 c# executable files. First one, lets say A is the target, Second one B, is the injector.
The purpose is to inject the dll and start harmony to patch DateTime.Now used in A.

I used another library and the injection works perfectly, even the starting code for harmony is working but the problem is that i cannot get the Assemblies of Executable A because they are in another AppDomain so i cannot patch them.

The question is: Is it possible for Harmony to patch all assemblies in other AppDpomains?

**Comment by denikson** [comment]
Greetings! Pardon the late response! 

**Disclaimer**: The following is based on my general experience with programming and studying application domains. I haven't yet tried to do runtime patching over application domain boundaries, which means that the actual conclusions might not be true until I actually test it properly.

Patching across application domains is a bit tricky as each one is supposed to be isolated from each other. That is, assemblies loaded into application domain A should not be visible or directly usable in application domain B without you explicitly loading them. 

However, the actual implementations application domains differs between the runtime implementations ans runtime versions: for instance, in older versions of mono (for example ones used in Unity 5.x) application domains are so lightly defined that you can easily switch application domains inside a method on the fly or manipulate any loaded application domain. On the other hand, in CoreCLR the notion of application domains exists only on API level while the runtime itself does not support them.

Nevertheless, for all intents and purposes you can think of application domains as [lightweight processes within a single process](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/2bh4z9hs(v=vs.90)). The main benefit of using application domains over separate processes is that you can communicate between them more easily than via some kind of IPC.

So, how do you patch assemblies in other application domains? The same way you patch assemblies in another process! That is, you

1. load your assembly into the other application domain (for example, via [`AppDomain.Load`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.load?view=netcore-3.1));
2. create an instance that is able to communicate with the original application domain (this can be achieved via [`CreateInstanceAndUnwrap`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.createinstanceandunwrap?redirectedfrom=MSDN&view=netcore-3.1#overloads) which allows to create an object and a special proxy that allows you to make method calls over application domain boundaries)
3. call `Patch` in the target application domain

[AppDomain usage example on MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain?redirectedfrom=MSDN&view=netcore-3.1#examples) provides a basic outline on how the aforementioned an work out.


All in all, it should be ideally possible to use HarmonyX across application domains as long as you perform correct marshaling. I do implore you to provide more info on your approach of applying HarmonyX patches over application domains. That way there is a concrete thing to test so that we know what to fix.

**Comment by denikson** [comment]
Closing this issue as stale. Right now Harmony does not support patching accross AppDomains either: pardeike/Harmony#322.

Since the main use case for HarmonyX is for modding Unity games that nearly never rely on cross-AppDomain patching, it is highly unlikely that we will specifically support this feature either in all its entirety (unless using the mono hacks outlined above).

If AppDomain patching is really needed, I suggest taking the approach outlined earlier. To recap, it involves loading Harmony in the target AppDomain, applying the patch there and then marshaling possible callbacks to the original assembly using MarshalByRef objects.
