### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by EvaisaGiac** [BepInEx/HarmonyX#17]
When trying to run harmony.PatchAll() BepInEx throws the following error:

```
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
tk2dTileMap:Awake()
```

This is happening in the game Monster Sanctuary.
Am I doing something wrong? Like my application settings for my plugin or something?

**Comment by denikson** [comment]
Greetings!

Based on the stack trace, the issue is not related to HarmonyX, but rather BepInEx and how your plugin is set up.
I'll address the issue here, but next time please create issues related to BepInEx in [BepInEx repo instead](https://github.com/BepInEx/BepInEx).

Since the error actually happens when your plugin is loaded, the problem is likely in your plugin project setup.  
Monster Sanctuary is using normal .NET Framework -equivalent API (as evidenced by lack of `netstandard.dll` in game's `_Data\Managed` folder). BepInEx core DLLs themselves are built to support both .NET Standard and .NET Framework APIs, so it leaves only your plugin DLL.

Make sure your plugin is built targeting .NET Framework and not .NET Standard. This is well documented in [BepInEx plugin development documentation](https://bepinex.github.io/bepinex_docs/master/articles/dev_guide/plugin_tutorial/1_setup.html#creating-a-solution).
In nutshell, check version of `mscorlib.dll` in game's `Managed` folder: if it's `4.0.0.0` or higher, you can usually target .NET Framework 4.6; in case of lower versions target .NET Framework 3.5. If you are unsure, targeting .NET Framework 3.5 is always a safe bet (although you won't get all available API and there can be problems with referencing some game DLLs).

Refer to the documentation of the development tools you use on how to change the target framework.

**Comment by EvaisaGiac** [comment]
Ah I see, Thank you.
Sorry I assumed it was HarmonyX related because it happened when calling a HarmonyX function, just running a Debug.Log("test") inside of Awake() worked fine and printed to the BepInEx console so my assumption was that everything else was working fine.

**Comment by denikson** [comment]
> Sorry I assumed it was HarmonyX related because it happened when calling a HarmonyX function

This most likely happened because when calling PatchAll, your assembly happened to reference some type that in .NET Standard is part of `netstandard.dll` which added the assembly as a dependency to your plugin DLL. Same will happen if you use something like `StringBuilder` API.

One way to check it is via tools like ilSpy or dnSpy which allow you to look at the contents of managed DLLs. Very likely your plugin DLL has the `netstandard` as one of references when using PatchAll which is indicative of plugin being built against .NET Standard API.

**Comment by EvaisaGiac** [comment]
Yep it works now!
Thank you so much ❤️ Sorry again for posting in the wrong repo.
